//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeepSeekAssistantVSPackage
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string DeepSeekAssistantVSPackagePackageString = "b6216745-f7c2-486a-848d-5d89b93666f9";
        public const string DeepSeekAssistantVSPackagePackageCmdSetString = "2c93c2f5-3df3-44be-b847-cfea5db0fd6d";
        public static Guid DeepSeekAssistantVSPackagePackage = new Guid(DeepSeekAssistantVSPackagePackageString);
        public static Guid DeepSeekAssistantVSPackagePackageCmdSet = new Guid(DeepSeekAssistantVSPackagePackageCmdSetString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int OpenDeepSeekChatCommandId = 0x0100;
    }
}